## Word Embedding


- 단어 임베딩을 계산하는 튜토리얼입니다.
- **참고문헌** : https://github.com/DerekChia/word2vec_numpy

### 말뭉치 읽어들이기

형태소 분석은 이미 수행되어 있다고 가정합니다

In [87]:
text = "1 8 3 9 년 바그너 는 괴테 의 파우스트 을 처음 읽 고 그 내용 에 마음 이 끌려 이 를 소재 로 해서 하나 의 교향곡 을 쓰 려는 뜻 을 갖 는다 . 이 시기 바그너 는 1 8 3 8 년 에 빛 독촉 으로 산전수전 을 다 걲은 상황 이 라 좌절 과 실망 에 가득 했으며 메피스토펠레스 를 만나 는 파우스트 의 심경 에 공감 했 다고 한다 . 또한 파리 에서 아 브네 크 의 지휘 로 파리 음악원 관현악단 이 연주 하 는 베토벤 의 교향곡 9 번 을 듣 고 깊 은 감명 을 받 았 는데 , 이것 이 이듬해 1 월 에 파우스트 의 서곡 으로 쓰여진 이 작품 에 조금 이 라도 영향 을 끼쳤 으리라는 것 은 의심 할 여지 가 없 다 . 여기 의 라단조 조성 의 경우 에 도 그 의 전기 에 적혀 있 는 것 처럼 단순 한 정신 적 피로 나 실의 가 반영 된 것 이 아니 라 베토벤 의 합창 교향곡 조성 의 영향 을 받 은 것 을 볼 수 있 다 . 그렇게 교향곡 작곡 을 1 8 3 9 년 부터 4 0 년 에 걸쳐 파리 에서 착수 했으나 1 악장 을 쓴 뒤 에 중단 했 다 . 또한 작품 의 완성 과 동시 에 그 는 이 서곡 ( 1 악장 ) 을 파리 음악원 의 연주회 에서 연주 할 파트 보 까지 준비 하 였으나 , 실제로 는 이루 어 지지 는 않 았 다 . 결국 초연 은 4 년 반 이 지난 후 에 드레스덴 에서 연주 되 었 고 재연 도 이루 어 졌 지만 , 이후 에 그대로 방치 되 고 말 았 다 . 그 사이 에 그 는 리엔치 와 방황 하 는 네덜란드인 을 완성 하 고 탄호이저 에 도 착수 하 는 등 분주 한 시간 을 보냈 는데 , 그런 바쁜 생활 이 이 곡 을 잊 게 한 것 이 아닌가 하 는 의견 도 있 다 . 바그너 는 괴테 의 파우스트 를 읽 고 무엇 을 쓰 고자 했 는가 ? 교향곡 바그너 는 교향곡 작곡 을 어디 까지 쓴 뒤 에 중단 했 는가 ? 1 악장 바그너 가 파우스트 서곡 을 쓸 때 어떤 곡 의 영향 을 받 았 는가 ? 베토벤 의 교향곡 9 번 1 8 3 9 년 바그너 가 교향곡 의 소재 로 쓰 려고 했 던 책 은 ? 파우스트 파우스트 서곡 의 라단조 조성 이 영향 을 받 은 베토벤 의 곡 은 ? 합창 교향곡 바그너 가 파우스트 를 처음 으로 읽 은 년 도 는 ? 1 8 3 9 바그너 가 처음 교향곡 작곡 을 한 장소 는 ? 파리 바그너 의 1 악장 의 초연 은 어디 서 연주 되 었 는가 ? 드레스 덴 한편 1 8 4 0 년 부터 바그너 와 알 고 지내 던 리스트 가 잊혀져 있 던 1 악장 을 부활 시켜 1 8 5 2 년 에 바이마르 에서 연주 했 다 . 이것 을 계기 로 바그너 도 이 작품 에 다시 관심 을 갖 게 되 었 고 , 그 해 9 월 에 는 총보 의 반환 을 요구 하 여 이 를 서곡 으로 간추린 다음 수정 을 했 고 브라이트 코프 흐 & 헤르 텔 출판사 에서 출판 할 개정판 도 준비 했 다 . 1 8 5 3 년 5 월 에 는 리스트 가 이 작품 이 수정 되 었 다는 것 을 인정 했 지만 , 끝내 바그너 의 출판 계획 은 무산 되 고 말 았 다 . 이후 1 8 5 5 년 에 리스트 가 자신 의 작품 파우스트 교향곡 을 거의 완성 하 여 그 사실 을 바그너 에게 알렸 고 , 바그너 는 다시 개정 된 총보 를 리스트 에게 보내 고 브라이트 코프 흐 & 헤르 텔 출판사 에 는 2 0 루이 의 금 을 받 고 팔 았 다 . 또한 그 의 작품 을 “ 하나하나 의 음표 가 시인 의 피 로 쓰여졌 다 ” 며 극찬 했 던 한스 폰 뷜로 가 그것 을 피아노 독주 용 으로 편곡 했 는데 , 리스트 는 그것 을 약간 변형 되 었 을 뿐 이 라고 지적 했 다 . 이 서곡 의 총보 첫머리 에 는 파우스트 1 부 의 내용 중 한 구절 을 인용 하 고 있 다 . 바그너 의 작품 을 시인 의 피 로 쓰여졌 다고 극찬 한 것 은 누구 인가 ? 한스 폰 뷜로 잊혀져 있 는 파우스트 서곡 1 악장 을 부활 시킨 것 은 누구 인가 ? 리스트 바그너 는 다시 개정 된 총보 를 얼마 를 받 고 팔 았 는가 ? 2 0 루이 의 금 파우스트 교향곡 을 부활 시킨 사람 은 ? 리스트 파우스트 교향곡 을 피아노 독주 용 으로 편곡 한 사람 은 ? 한스 폰 뷜로 1 악장 을 부활 시켜 연주 한 사람 은 ? 리스트 파우스트 교향곡 에 감탄 하 여 피아노 곡 으로 편곡 한 사람 은 ? 한스 폰 뷜로 리스트 가 바그너 와 알 게 된 연도 는 ? 1 8 4 0 년 이 작품 은 라단조 , Sehr gehalten ( 아주 신중 하 게 ) , 4 / 4 박자 의 부드러운 서주 로 서주 로 시작 되 는데 , 여기 에 는 주요 주제 , 동기 의 대부분 이 암시 , 예고 되 어 있 다 . 첫 부분 의 저음 주제 는 주요 주제 ( 고뇌 와 갈망 동기 , 청춘 의 사랑 동기 ) 를 암시 하 고 있 으며 , 제 1 바이올린 으로 더욱 명확 하 게 나타난다 . 또한 그것 을 이어받 는 동기 도 중요 한 역할 을 한다 . 여기 에 새로운 소재 가 더 해진 뒤 에 새로운 주제 도 연주 된다 . 주요부 는 Sehr bewegt ( 아주 격동 적 으로 ) , 2 / 2 박자 의 자유 로운 소나타 형식 으로 매우 드라마틱 한 구상 과 유기 적 인 구성 을 하 고 있 다 . 여기 에 는 지금 까지 의 주제 나 소재 외 에 도 오보에 에 의한 선율 과 제 2 주제 를 떠올리 게 하 는 부차 적 인 주제 가 더 해 지 는데 , 중간부 에서 는 약보 3 이 중심 이 되 고 제 2 주제 는 축소 된 재현부 에서 D 장조 로 재현 된다 . 마지막 에 는 주요 주제 를 회상 하 면서 조용히 마친다 . 서주 에 는 무엇 이 암시 되 어 있 는가 ? 주제 , 동기 첫 부분 에 는 어떤 악기 를 사용 해 더욱 명확 하 게 나타내 는가 ? 제 1 바이올린 주요부 는 어떤 형식 으로 되 어 있 는가 ? 소나타 형식 첫 부분 의 주요 주제 를 암시 하 는 주제 는 ? 저음 주제 제 2 주제 의 축소 된 재현부 의 조성 은 ? D 장조 곡 이 시작 할 때 의 박자 는 ? 4 / 4 박자 이 곡 의 주요 주제 는 ? 고뇌 와 갈망 동기 , 청춘 의 사랑 동기 제 2 주제 에선 무슨 장조 로 재현 되 는가 ? D 장조"
corpus = [[word for word in text.split()]]

In [88]:
corpus

[['1',
  '8',
  '3',
  '9',
  '년',
  '바그너',
  '는',
  '괴테',
  '의',
  '파우스트',
  '을',
  '처음',
  '읽',
  '고',
  '그',
  '내용',
  '에',
  '마음',
  '이',
  '끌려',
  '이',
  '를',
  '소재',
  '로',
  '해서',
  '하나',
  '의',
  '교향곡',
  '을',
  '쓰',
  '려는',
  '뜻',
  '을',
  '갖',
  '는다',
  '.',
  '이',
  '시기',
  '바그너',
  '는',
  '1',
  '8',
  '3',
  '8',
  '년',
  '에',
  '빛',
  '독촉',
  '으로',
  '산전수전',
  '을',
  '다',
  '걲은',
  '상황',
  '이',
  '라',
  '좌절',
  '과',
  '실망',
  '에',
  '가득',
  '했으며',
  '메피스토펠레스',
  '를',
  '만나',
  '는',
  '파우스트',
  '의',
  '심경',
  '에',
  '공감',
  '했',
  '다고',
  '한다',
  '.',
  '또한',
  '파리',
  '에서',
  '아',
  '브네',
  '크',
  '의',
  '지휘',
  '로',
  '파리',
  '음악원',
  '관현악단',
  '이',
  '연주',
  '하',
  '는',
  '베토벤',
  '의',
  '교향곡',
  '9',
  '번',
  '을',
  '듣',
  '고',
  '깊',
  '은',
  '감명',
  '을',
  '받',
  '았',
  '는데',
  ',',
  '이것',
  '이',
  '이듬해',
  '1',
  '월',
  '에',
  '파우스트',
  '의',
  '서곡',
  '으로',
  '쓰여진',
  '이',
  '작품',
  '에',
  '조금',
  '이',
  '라도',
  '영향',
  '을',
  '끼쳤',
  '으리라는',
  '것',
  '은',
  '의심',


### 하이퍼 파라메터 설정

- `window size` : 타겟단어 앞뒤로 몇 개의 단어를 볼지
- `dimension` : word2vec 임베딩의 차원 수
- `epochs` : 말뭉치를 몇 번 학습할지
- `learning_rate` : 학습률

In [89]:
settings = {
    'window_size': 2,
    'dimension': 10,
    'epochs': 1000,
    'learning_rate': 0.05
}

### Vocabulary 만들기

단어 임베딩 구축 대상 어휘 목록을 만듭니다.

In [90]:
from collections import defaultdict
word_counts = defaultdict(int)

In [91]:
for row in corpus:
    for word in row:
        word_counts[word] += 1

In [92]:
word_counts

defaultdict(int,
            {'1': 21,
             '8': 11,
             '3': 7,
             '9': 7,
             '년': 12,
             '바그너': 17,
             '는': 41,
             '괴테': 2,
             '의': 45,
             '파우스트': 14,
             '을': 43,
             '처음': 3,
             '읽': 3,
             '고': 18,
             '그': 8,
             '내용': 2,
             '에': 33,
             '마음': 1,
             '이': 28,
             '끌려': 1,
             '를': 13,
             '소재': 4,
             '로': 10,
             '해서': 1,
             '하나': 1,
             '교향곡': 14,
             '쓰': 3,
             '려는': 1,
             '뜻': 1,
             '갖': 2,
             '는다': 1,
             '.': 21,
             '시기': 1,
             '빛': 1,
             '독촉': 1,
             '으로': 11,
             '산전수전': 1,
             '다': 16,
             '걲은': 1,
             '상황': 1,
             '라': 2,
             '좌절': 1,
             '과': 4,
             '실망': 1,
             '가

In [93]:
vocab_size = len(word_counts.keys())
vocab = list(word_counts.keys())

In [94]:
vocab_size

341

In [95]:
vocab

['1',
 '8',
 '3',
 '9',
 '년',
 '바그너',
 '는',
 '괴테',
 '의',
 '파우스트',
 '을',
 '처음',
 '읽',
 '고',
 '그',
 '내용',
 '에',
 '마음',
 '이',
 '끌려',
 '를',
 '소재',
 '로',
 '해서',
 '하나',
 '교향곡',
 '쓰',
 '려는',
 '뜻',
 '갖',
 '는다',
 '.',
 '시기',
 '빛',
 '독촉',
 '으로',
 '산전수전',
 '다',
 '걲은',
 '상황',
 '라',
 '좌절',
 '과',
 '실망',
 '가득',
 '했으며',
 '메피스토펠레스',
 '만나',
 '심경',
 '공감',
 '했',
 '다고',
 '한다',
 '또한',
 '파리',
 '에서',
 '아',
 '브네',
 '크',
 '지휘',
 '음악원',
 '관현악단',
 '연주',
 '하',
 '베토벤',
 '번',
 '듣',
 '깊',
 '은',
 '감명',
 '받',
 '았',
 '는데',
 ',',
 '이것',
 '이듬해',
 '월',
 '서곡',
 '쓰여진',
 '작품',
 '조금',
 '라도',
 '영향',
 '끼쳤',
 '으리라는',
 '것',
 '의심',
 '할',
 '여지',
 '가',
 '없',
 '여기',
 '라단조',
 '조성',
 '경우',
 '도',
 '전기',
 '적혀',
 '있',
 '처럼',
 '단순',
 '한',
 '정신',
 '적',
 '피로',
 '나',
 '실의',
 '반영',
 '된',
 '아니',
 '합창',
 '볼',
 '수',
 '그렇게',
 '작곡',
 '부터',
 '4',
 '0',
 '걸쳐',
 '착수',
 '했으나',
 '악장',
 '쓴',
 '뒤',
 '중단',
 '완성',
 '동시',
 '(',
 ')',
 '연주회',
 '파트',
 '보',
 '까지',
 '준비',
 '였으나',
 '실제로',
 '이루',
 '어',
 '지지',
 '않',
 '결국',
 '초연',
 '반',
 '지난',
 '후',
 '드레스덴',
 '되',
 '

컴퓨터는 단어를 이해하지 못하므로, 인덱스로 바꿔줘야 합니다. (1) 단어를 넣으면 인덱스 값을 반환하는 dictionary `word_to_index`, (2) 인덱스 값을 넣으면 단어를 반환하는 dictionary `index_to_word`를 만듭시다

In [96]:
word_to_index = dict((word, i) for i, word in enumerate(vocab))
index_to_word = dict((i, word) for i, word in enumerate(vocab))

In [97]:
word_to_index

{'1': 0,
 '8': 1,
 '3': 2,
 '9': 3,
 '년': 4,
 '바그너': 5,
 '는': 6,
 '괴테': 7,
 '의': 8,
 '파우스트': 9,
 '을': 10,
 '처음': 11,
 '읽': 12,
 '고': 13,
 '그': 14,
 '내용': 15,
 '에': 16,
 '마음': 17,
 '이': 18,
 '끌려': 19,
 '를': 20,
 '소재': 21,
 '로': 22,
 '해서': 23,
 '하나': 24,
 '교향곡': 25,
 '쓰': 26,
 '려는': 27,
 '뜻': 28,
 '갖': 29,
 '는다': 30,
 '.': 31,
 '시기': 32,
 '빛': 33,
 '독촉': 34,
 '으로': 35,
 '산전수전': 36,
 '다': 37,
 '걲은': 38,
 '상황': 39,
 '라': 40,
 '좌절': 41,
 '과': 42,
 '실망': 43,
 '가득': 44,
 '했으며': 45,
 '메피스토펠레스': 46,
 '만나': 47,
 '심경': 48,
 '공감': 49,
 '했': 50,
 '다고': 51,
 '한다': 52,
 '또한': 53,
 '파리': 54,
 '에서': 55,
 '아': 56,
 '브네': 57,
 '크': 58,
 '지휘': 59,
 '음악원': 60,
 '관현악단': 61,
 '연주': 62,
 '하': 63,
 '베토벤': 64,
 '번': 65,
 '듣': 66,
 '깊': 67,
 '은': 68,
 '감명': 69,
 '받': 70,
 '았': 71,
 '는데': 72,
 ',': 73,
 '이것': 74,
 '이듬해': 75,
 '월': 76,
 '서곡': 77,
 '쓰여진': 78,
 '작품': 79,
 '조금': 80,
 '라도': 81,
 '영향': 82,
 '끼쳤': 83,
 '으리라는': 84,
 '것': 85,
 '의심': 86,
 '할': 87,
 '여지': 88,
 '가': 89,
 '없': 90,
 '여기': 91,
 '라단조': 92,
 '조성'

In [98]:
index_to_word

{0: '1',
 1: '8',
 2: '3',
 3: '9',
 4: '년',
 5: '바그너',
 6: '는',
 7: '괴테',
 8: '의',
 9: '파우스트',
 10: '을',
 11: '처음',
 12: '읽',
 13: '고',
 14: '그',
 15: '내용',
 16: '에',
 17: '마음',
 18: '이',
 19: '끌려',
 20: '를',
 21: '소재',
 22: '로',
 23: '해서',
 24: '하나',
 25: '교향곡',
 26: '쓰',
 27: '려는',
 28: '뜻',
 29: '갖',
 30: '는다',
 31: '.',
 32: '시기',
 33: '빛',
 34: '독촉',
 35: '으로',
 36: '산전수전',
 37: '다',
 38: '걲은',
 39: '상황',
 40: '라',
 41: '좌절',
 42: '과',
 43: '실망',
 44: '가득',
 45: '했으며',
 46: '메피스토펠레스',
 47: '만나',
 48: '심경',
 49: '공감',
 50: '했',
 51: '다고',
 52: '한다',
 53: '또한',
 54: '파리',
 55: '에서',
 56: '아',
 57: '브네',
 58: '크',
 59: '지휘',
 60: '음악원',
 61: '관현악단',
 62: '연주',
 63: '하',
 64: '베토벤',
 65: '번',
 66: '듣',
 67: '깊',
 68: '은',
 69: '감명',
 70: '받',
 71: '았',
 72: '는데',
 73: ',',
 74: '이것',
 75: '이듬해',
 76: '월',
 77: '서곡',
 78: '쓰여진',
 79: '작품',
 80: '조금',
 81: '라도',
 82: '영향',
 83: '끼쳤',
 84: '으리라는',
 85: '것',
 86: '의심',
 87: '할',
 88: '여지',
 89: '가',
 90: '없',
 91: '여기',
 92: '라단조',
 93: 

## One-hot-representation 만들기

단어를 넣으면 원핫 벡터를 만들어주는 함수를 만들어 봅시다. 

In [99]:
import numpy as np
a=np.zeros(10) # 0 벡터를 만들어주는 함수 np.zeros

In [100]:
a[3] = 1

In [101]:
a

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [102]:
def word2onehot(word):
    word_vec = np.zeros(vocab_size)
    word_index = word_to_index[word]
    word_vec[word_index] = 1
    return word_vec
# word가 1인값만 리턴하는 벡터 만들어 줌 

In [103]:
word2onehot("바그너")

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

### Skip-Gram 학습데이터 만들기

Skip-Gram은 `타겟 단어(target word)`로 `주변 단어(context word)`를 맞추는 과정에서 학습하는 모델입니다. `(타겟 단어, 주변 단어)` 쌍을 만들어 봅시다.

In [104]:
def generate_skipgram_training_data():
    training_data = []
    for sentence in corpus:
        sent_len = len(sentence)
        for i, word in enumerate(sentence):
            w_target = sentence[i]
            for j in range(i - settings['window_size'], i + settings['window_size'] + 1):
                if j != i and j <= sent_len - 1 and j >= 0:
                    w_context = sentence[j]
                    training_data.append([w_target, w_context])
    return training_data

In [105]:
train_data = generate_skipgram_training_data()

In [106]:
train_data # window 사이즈는 2개로 보고, 타겟과 컨텐츠를 쌍으로 묶어높음 

[['1', '8'],
 ['1', '3'],
 ['8', '1'],
 ['8', '3'],
 ['8', '9'],
 ['3', '1'],
 ['3', '8'],
 ['3', '9'],
 ['3', '년'],
 ['9', '8'],
 ['9', '3'],
 ['9', '년'],
 ['9', '바그너'],
 ['년', '3'],
 ['년', '9'],
 ['년', '바그너'],
 ['년', '는'],
 ['바그너', '9'],
 ['바그너', '년'],
 ['바그너', '는'],
 ['바그너', '괴테'],
 ['는', '년'],
 ['는', '바그너'],
 ['는', '괴테'],
 ['는', '의'],
 ['괴테', '바그너'],
 ['괴테', '는'],
 ['괴테', '의'],
 ['괴테', '파우스트'],
 ['의', '는'],
 ['의', '괴테'],
 ['의', '파우스트'],
 ['의', '을'],
 ['파우스트', '괴테'],
 ['파우스트', '의'],
 ['파우스트', '을'],
 ['파우스트', '처음'],
 ['을', '의'],
 ['을', '파우스트'],
 ['을', '처음'],
 ['을', '읽'],
 ['처음', '파우스트'],
 ['처음', '을'],
 ['처음', '읽'],
 ['처음', '고'],
 ['읽', '을'],
 ['읽', '처음'],
 ['읽', '고'],
 ['읽', '그'],
 ['고', '처음'],
 ['고', '읽'],
 ['고', '그'],
 ['고', '내용'],
 ['그', '읽'],
 ['그', '고'],
 ['그', '내용'],
 ['그', '에'],
 ['내용', '고'],
 ['내용', '그'],
 ['내용', '에'],
 ['내용', '마음'],
 ['에', '그'],
 ['에', '내용'],
 ['에', '마음'],
 ['에', '이'],
 ['마음', '내용'],
 ['마음', '에'],
 ['마음', '이'],
 ['마음', '끌려'],
 ['이', '에'],
 ['이', '마음'],
 ['이'

In [107]:
len(train_data) #길이가 얼마 안 되는 데도 4726건이 나옴 

4726

## parameter initialization

Skip-Gram 모델의 trained parameter를 초기화합니다. $\mathbf{U}$는 타겟 단어, $\mathbf{V}$는 주변 단어와 관련한 행렬입니다 

In [108]:
# skip-gram의 매개변수 u랑 v를 초기화 
np.random.seed(7) # seed를 고정해야 초기화 할 때마다 같은 값이 나옴. 7은 랜덤으로 정하신거 (럭키세븐)

In [109]:
parameters = {}
parameters["U"] = np.random.randn(vocab_size, settings["dimension"]) * 0.01 # 매트릭스 초기화 (vovac 바이 d)
parameters["V"] = np.random.randn(settings["dimension"], vocab_size) * 0.01 #(d 바이 vocab)

In [110]:
parameters["U"]

array([[ 0.01690526, -0.00465937,  0.0003282 , ..., -0.01754724,
         0.01017658,  0.00600499],
       [-0.00625429, -0.00171548,  0.00505299, ...,  0.00123881,
         0.0027446 , -0.01526525],
       [ 0.016507  ,  0.00154336, -0.0038714 , ..., -0.02288315,
         0.01049397, -0.00416474],
       ...,
       [-0.01654933, -0.01438212, -0.00949831, ..., -0.00365312,
         0.00744186,  0.00951336],
       [-0.01278959, -0.01704521,  0.01399392, ...,  0.00577181,
         0.00493717,  0.01216505],
       [-0.00105921,  0.003862  ,  0.00308768, ...,  0.00286352,
         0.01099796, -0.01029174]])

In [111]:
parameters["V"]

array([[-0.00696121,  0.0093482 , -0.00300656, ..., -0.00050532,
        -0.00293001,  0.0057444 ],
       [ 0.00450133,  0.01800249,  0.0143195 , ...,  0.00776067,
        -0.01583356, -0.00202858],
       [ 0.00298211,  0.00252365,  0.00381421, ...,  0.00545599,
         0.01944487,  0.01329373],
       ...,
       [-0.00174862,  0.00206436,  0.01228888, ..., -0.01491195,
        -0.00902887, -0.00834019],
       [ 0.00116874, -0.00764041, -0.01814553, ...,  0.00327103,
         0.00074978,  0.00510185],
       [-0.00153577,  0.00731621,  0.01359505, ...,  0.01342015,
        -0.01051363,  0.00860396]])

파라메터 업데이트 과정을 추적하기 위해 초기 행렬 값을 `old_param`에 복사해 둡니다.

In [112]:
import copy
old_param = {'U': copy.deepcopy(parameters["U"]), 'V': copy.deepcopy(parameters["V"])}

## Forward Computation

Skip-Gram은 타깃 단어($t$)로 문맥 단어($c$)를 맞추는 과정에서 학습됩니다.

𝐔 는 타겟 단어, 𝐕는 주변 단어와 관련한 행렬입니다.

$\mathbf{u_{t}} = \text{onehot}_{t} \cdot \mathbf{U} \\
\text{logit} = \mathbf{u_{t}} \cdot \mathbf{V} \\
P(c|t) = \text{softmax(logit)}$
- 원 핫 벡터를 구하면 행렬의 타겟 워드만 나오는 참조 현상이 나옴 ( 사진 참고 )

In [113]:
def forward_computation(target_word_onehot_vectors, parameters):
    # target_word_onehot_vectors shape : [batch_size, vocab_size]
    # U shape : [vocab_size, settings["dimension"]]
    # target_word_vectors shape : [batch_size, settings["dimension"]]
    target_word_vectors = np.dot(target_word_onehot_vectors, parameters["U"])
    # logits shape : [batch_size, vocab_size]
    logits = np.dot(target_word_vectors, parameters["V"])
    # 0.0001 : underflow 방지
    softmax_probs = softmax(logits) #forword computation 
    #softmax_probs = np.divide(np.exp(logits), np.sum(np.exp(logits), axis=0, keepdims=True) + 0.001)
    if len(target_word_vectors.shape) == 1:
        target_word_vectors = np.expand_dims(target_word_vectors, axis=0)
    # 나중에 backprop을 하기 위한 데이터 캐시
    caches = {"target_word_vectors": target_word_vectors}
    return softmax_probs, caches

## softmax 함수 정의

$\exp$는 1보다 크기 때문에 지수승을 거듭하면 지나치게 큰 수가 나옴

이에 입력 벡터 $x$의 최대값을 $x$에서 빼줌

이렇게 하더라도 $x$ 벡터 요소들의 대소관계는 바뀌지 않음

In [114]:
np.exp(2000)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


inf

In [115]:
def softmax(x, axis=1):
    x = x - x.max(axis=axis, keepdims=True) # x에서 최대값 x를 빰 (대소 관계가 바뀌지 않음!!!)
    y = np.exp(x)
    return y / y.sum(axis=axis, keepdims=True)

In [116]:
# 예시
softmax(np.array([[1,2,3],[14,5,6]]))

array([[9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [9.99541338e-01, 1.23353201e-04, 3.35308764e-04]])

In [117]:
np.sum(softmax(np.array([[1,2,3], [14,5,6]]))[0])

0.9999999999999999

In [118]:
np.sum(softmax(np.array([[1,2,3], [14,5,6]]))[1])

1.0

## Loss Computation

In [119]:
def cross_entropy(target, softmax_prob): #target = 워드랑 헷갈라지 말지. label(정답), 예측한 값 -> 이 둘의 차이가 cross entropy
    """
    targe: shape (batch_size, vocab_size)
    softmax_prob: output out of softmax. shape: (batch_size, vocab_size)
    """
    batch_size = softmax_prob.shape[0]
    cost = -(1 / batch_size) * np.sum(np.sum(target * np.log(softmax_prob + 0.001), axis=0, keepdims=True), axis=1)
    return cost

## Back Propagation

https://ratsgo.github.io/deep%20learning/2017/10/02/softmax/

In [120]:
def softmax_backward(target, softmax_prob):
    """
    target: labels onehot vector of training data. shape: (batch_size, vocab_size)
    softmax_prob: output out of softmax. shape: (batch_size, vocab_size)
    """
    return softmax_prob - target
# 최초의 그레이던트를 구하는 방법 : softmax_prob에서 정답(target)을 빼누다 

In [121]:
def dense_backward(dL_dlogits, caches):
    V = parameters['V']
    batch_size = dL_dlogits.shape[0]
    target_word_vectors = caches['target_word_vectors']
    dL_dtarget = (1 / batch_size) * np.dot(dL_dlogits, V.T)
    dL_dV = np.dot(dL_dlogits.T, target_word_vectors)
    return dL_dtarget, dL_dV
# 2,3번 구하는 거. ut와 v의 상대 로컬 곱하는 거 

## parameter update

$\mathbf{u}_{t}$는 $\mathbf{U}$ 행렬에서 타겟 단어(t)에 해당하는 행 벡터를 참조(look)한 것

따라서 $U$ 행렬의 t에 해당하는 행벡터만 업데이트함
- v는 한번 업뎃할 때마다 행렬 전체가 업뎃 됨
- ut는 그 타겟만 업뎃됨 

In [122]:
def update_parameters(parameters, dL_dtarget, dL_dV,
                      learning_rate, target_words_idexes):
    parameters['V'] -= learning_rate * dL_dV.T #v는 한번 업뎃할 때마다 행렬 전체 업뎃(덮어씀)
    if type(target_words_idexes) == list: # 행벡터 하나씩 업뎃하는 거라서 for문을 돌림 
        for target_word_idx, target_word_update in zip(target_words_idexes, dL_dtarget):
            parameters['U'][[target_word_idx], :] -= learning_rate * target_word_update
    else:
        parameters['U'][[target_words_idexes], :] -= learning_rate * dL_dtarget

## 계산 예시

In [123]:
train_data

[['1', '8'],
 ['1', '3'],
 ['8', '1'],
 ['8', '3'],
 ['8', '9'],
 ['3', '1'],
 ['3', '8'],
 ['3', '9'],
 ['3', '년'],
 ['9', '8'],
 ['9', '3'],
 ['9', '년'],
 ['9', '바그너'],
 ['년', '3'],
 ['년', '9'],
 ['년', '바그너'],
 ['년', '는'],
 ['바그너', '9'],
 ['바그너', '년'],
 ['바그너', '는'],
 ['바그너', '괴테'],
 ['는', '년'],
 ['는', '바그너'],
 ['는', '괴테'],
 ['는', '의'],
 ['괴테', '바그너'],
 ['괴테', '는'],
 ['괴테', '의'],
 ['괴테', '파우스트'],
 ['의', '는'],
 ['의', '괴테'],
 ['의', '파우스트'],
 ['의', '을'],
 ['파우스트', '괴테'],
 ['파우스트', '의'],
 ['파우스트', '을'],
 ['파우스트', '처음'],
 ['을', '의'],
 ['을', '파우스트'],
 ['을', '처음'],
 ['을', '읽'],
 ['처음', '파우스트'],
 ['처음', '을'],
 ['처음', '읽'],
 ['처음', '고'],
 ['읽', '을'],
 ['읽', '처음'],
 ['읽', '고'],
 ['읽', '그'],
 ['고', '처음'],
 ['고', '읽'],
 ['고', '그'],
 ['고', '내용'],
 ['그', '읽'],
 ['그', '고'],
 ['그', '내용'],
 ['그', '에'],
 ['내용', '고'],
 ['내용', '그'],
 ['내용', '에'],
 ['내용', '마음'],
 ['에', '그'],
 ['에', '내용'],
 ['에', '마음'],
 ['에', '이'],
 ['마음', '내용'],
 ['마음', '에'],
 ['마음', '이'],
 ['마음', '끌려'],
 ['이', '에'],
 ['이', '마음'],
 ['이'

In [124]:
len(train_data)

4726

In [125]:
target_word, context_word = train_data[100]

In [126]:
target_word

'하나'

In [127]:
context_word

'교향곡'

In [128]:
word_to_index["교향곡"]

25

In [129]:
target_word_onehot_vector = word2onehot(target_word) #원핫 만들기

In [130]:
softmax_prob, caches = forward_computation([target_word_onehot_vector], parameters)

In [131]:
softmax_prob

array([[0.00293203, 0.00293162, 0.00293093, 0.00293153, 0.00293283,
        0.00293209, 0.00293283, 0.00293074, 0.00293305, 0.00293287,
        0.0029318 , 0.00293411, 0.00293432, 0.00293111, 0.00293305,
        0.00293158, 0.002934  , 0.00293199, 0.00293202, 0.00293263,
        0.00293226, 0.00293326, 0.0029315 , 0.00293195, 0.00293401,
        0.00293212, 0.00293461, 0.00293351, 0.00293321, 0.00293362,
        0.00293362, 0.00293318, 0.00293308, 0.00293203, 0.00293236,
        0.00293306, 0.00293215, 0.00293314, 0.00292944, 0.00293161,
        0.00293376, 0.00293186, 0.00293377, 0.00292922, 0.00293197,
        0.00293184, 0.0029318 , 0.00293278, 0.00293132, 0.0029322 ,
        0.00293371, 0.00293312, 0.00293204, 0.00293258, 0.00293168,
        0.0029321 , 0.00293185, 0.00293042, 0.00293296, 0.00293073,
        0.00293061, 0.00293407, 0.00293314, 0.00293318, 0.00293436,
        0.00293119, 0.00293302, 0.00293318, 0.00293431, 0.00293323,
        0.00293295, 0.00293346, 0.00293236, 0.00

In [132]:
vocab_size 

341

In [133]:
softmax_prob.shape #어휘 수만큼의 차원수  위의 vocab_size 341개와 동일 

(1, 341)

In [134]:
np.sum(softmax_prob) # 다 더하면 확률이니까 1 

0.9999999999999998

In [135]:
caches # 3번 구할 때 ut가 있어야 그레디언트를 구할 수 있는 데, 미리 ut를 저장해놓은 거 (나중에 백프롭 할 때 쓰려고)

{'target_word_vectors': array([[-0.00132788, -0.01899861,  0.01275362,  0.00019361,  0.00736378,
         -0.01172917,  0.01288204, -0.00588263, -0.00107667, -0.01401425]])}

In [136]:
context_word_onehot_vector = word2onehot(context_word)
loss = cross_entropy([context_word_onehot_vector], softmax_prob) #정답, 모델 예측값 넣은 후 차이를 loss 

In [137]:
context_word # 이값을 원핫으로 바꾼 게 정답 

'교향곡'

In [138]:
loss # 값이 크니까 작게 업데이트 하기 

array([5.53857547])

In [139]:
dL_dlogits = softmax_backward([context_word_onehot_vector], softmax_prob) 
# 최초의 그레디언트 = 정답, 예측값을 소프트맥스 백워드 하기 

In [140]:
#softmax_prob랑 dl 비교
softmax_prob[0][:30]

array([0.00293203, 0.00293162, 0.00293093, 0.00293153, 0.00293283,
       0.00293209, 0.00293283, 0.00293074, 0.00293305, 0.00293287,
       0.0029318 , 0.00293411, 0.00293432, 0.00293111, 0.00293305,
       0.00293158, 0.002934  , 0.00293199, 0.00293202, 0.00293263,
       0.00293226, 0.00293326, 0.0029315 , 0.00293195, 0.00293401,
       0.00293212, 0.00293461, 0.00293351, 0.00293321, 0.00293362])

In [141]:
dL_dlogits[0][:30]
# 왼 쪽 맨 밑만 다름

array([ 0.00293203,  0.00293162,  0.00293093,  0.00293153,  0.00293283,
        0.00293209,  0.00293283,  0.00293074,  0.00293305,  0.00293287,
        0.0029318 ,  0.00293411,  0.00293432,  0.00293111,  0.00293305,
        0.00293158,  0.002934  ,  0.00293199,  0.00293202,  0.00293263,
        0.00293226,  0.00293326,  0.0029315 ,  0.00293195,  0.00293401,
       -0.99706788,  0.00293461,  0.00293351,  0.00293321,  0.00293362])

In [142]:
dL_dlogits.shape

(1, 341)

In [143]:
dL_dtarget, dL_dV = dense_backward(dL_dlogits, caches)

In [145]:
dL_dtarget #10차원짜리 벡터 - 과정 2번 이야기 (ut에 상대 로컬 v 곱하는 거)

array([[-0.00205106,  0.00558208,  0.00999908,  0.00605333,  0.00186556,
         0.00066968,  0.01463972,  0.01104665, -0.00122193,  0.00074777]])

In [144]:
dL_dtarget.shape #벡터 업데이트 

(1, 10)

In [146]:
dL_dV.shape  #행렬 업데이트 

(341, 10)

In [149]:
target_word

'하나'

In [150]:
target_word_idx = word_to_index[target_word]

In [151]:
update_parameters(parameters, dL_dtarget, dL_dV, 1000, target_word_idx) #1000을 넣은 이유는 도드라지게 보이려고함 
#learning_mate는 사실 작게 둬야하는 데, 잘 차이가 안 보이니까 그냥 1000 넣은 거임 

In [153]:
parameters["U"]

array([[ 0.01690526, -0.00465937,  0.0003282 , ..., -0.01754724,
         0.01017658,  0.00600499],
       [-0.00625429, -0.00171548,  0.00505299, ...,  0.00123881,
         0.0027446 , -0.01526525],
       [ 0.016507  ,  0.00154336, -0.0038714 , ..., -0.02288315,
         0.01049397, -0.00416474],
       ...,
       [-0.01654933, -0.01438212, -0.00949831, ..., -0.00365312,
         0.00744186,  0.00951336],
       [-0.01278959, -0.01704521,  0.01399392, ...,  0.00577181,
         0.00493717,  0.01216505],
       [-0.00105921,  0.003862  ,  0.00308768, ...,  0.00286352,
         0.01099796, -0.01029174]])

In [154]:
old_param["U"] #기존에 업뎃안된 파람을 미리 old_param으로 저장했었음 
# 타겟 워드에 해당하는 한 벡터만 업뎃 된거라서 이렇게 보면 업뎃 안 된 것처럼 보임 

array([[ 0.01690526, -0.00465937,  0.0003282 , ..., -0.01754724,
         0.01017658,  0.00600499],
       [-0.00625429, -0.00171548,  0.00505299, ...,  0.00123881,
         0.0027446 , -0.01526525],
       [ 0.016507  ,  0.00154336, -0.0038714 , ..., -0.02288315,
         0.01049397, -0.00416474],
       ...,
       [-0.01654933, -0.01438212, -0.00949831, ..., -0.00365312,
         0.00744186,  0.00951336],
       [-0.01278959, -0.01704521,  0.01399392, ...,  0.00577181,
         0.00493717,  0.01216505],
       [-0.00105921,  0.003862  ,  0.00308768, ...,  0.00286352,
         0.01099796, -0.01029174]])

In [156]:
parameters["U"][target_word_idx, :] #그래서 타겟 워드들만 보면 엄청 바뀌어져 있음

array([  2.04973576,  -5.60108198,  -9.98632726,  -6.05313916,
        -1.85819142,  -0.68140737, -14.62683441, -11.05253426,
         1.22085083,  -0.76178253])

In [161]:
old_param["U"][target_word_idx, :] #그래서 타겟 워드들만 보면 엄청 바뀌어져 있음

array([-0.00132788, -0.01899861,  0.01275362,  0.00019361,  0.00736378,
       -0.01172917,  0.01288204, -0.00588263, -0.00107667, -0.01401425])

In [162]:
parameters["V"]

array([[-0.00306784,  0.01324103,  0.00088535, ...,  0.00338744,
         0.00096626,  0.00963996],
       [ 0.06020578,  0.07369929,  0.0700031 , ...,  0.06345644,
         0.03991244,  0.05370724],
       [-0.03441184, -0.03486517, -0.03356574, ..., -0.03193213,
        -0.01797698, -0.02412128],
       ...,
       [ 0.0154994 ,  0.01931002,  0.02953045, ...,  0.00233339,
         0.00823202,  0.00891755],
       [ 0.00432557, -0.00448401, -0.01498988, ...,  0.00642736,
         0.00390896,  0.00826046],
       [ 0.03955438,  0.04840072,  0.05466981, ...,  0.0545039 ,
         0.03060718,  0.04971725]])

In [163]:
old_param["V"]

array([[-0.00696121,  0.0093482 , -0.00300656, ..., -0.00050532,
        -0.00293001,  0.0057444 ],
       [ 0.00450133,  0.01800249,  0.0143195 , ...,  0.00776067,
        -0.01583356, -0.00202858],
       [ 0.00298211,  0.00252365,  0.00381421, ...,  0.00545599,
         0.01944487,  0.01329373],
       ...,
       [-0.00174862,  0.00206436,  0.01228888, ..., -0.01491195,
        -0.00902887, -0.00834019],
       [ 0.00116874, -0.00764041, -0.01814553, ...,  0.00327103,
         0.00074978,  0.00510185],
       [-0.00153577,  0.00731621,  0.01359505, ...,  0.01342015,
        -0.01051363,  0.00860396]])

## train

In [164]:
parameters = {} #로스가 100 에폭(epochs)마다 한번씩 돌아가게 바꿈 # 정해진 에폭스가 되었을 때나 목표값이 나올 때 중단시킴.
parameters["U"] = np.random.randn(vocab_size, settings["dimension"]) * 0.01 #행렬 만들기
parameters["V"] = np.random.randn(settings["dimension"], vocab_size) * 0.01
target_word_onehot_vectors = [word2onehot(target_word) for target_word, context_word in train_data] #원핫 만들기
context_word_onehot_vectors = [word2onehot(context_word) for target_word, context_word in train_data]
target_words_idexes = [word_to_index[target_word] for target_word, context_word in train_data] #인덱스 주기 
for i in range(settings["epochs"]): #순방향 계산
    softmax_prob, caches = forward_computation(target_word_onehot_vectors, parameters) #로스 계산
    loss = cross_entropy(context_word_onehot_vectors, softmax_prob) #로스 최소화
    dL_dlogits = softmax_backward(context_word_onehot_vectors, softmax_prob) #로스를 백프롭으로 계산함
    dL_dtarget, dL_dV = dense_backward(dL_dlogits, caches)
    update_parameters(parameters, dL_dtarget, dL_dV, settings['learning_rate'], target_words_idexes) #업데이트 시킴
    if i % 100 == 0: 
        print(loss)

[5.53846865]
[5.48499423]
[4.92724913]
[4.56532669]
[4.31198761]
[4.1360291]
[4.00533694]
[3.89880004]
[3.81344803]
[3.74453286]


In [166]:
# 코사인 시밀러리티 구하기 (공책 설명 - 벡터 설명 보기) => 유닛 벡터 내적함을 보여주기 위해 
def most_similar(query_word, topn=3, embeddings=parameters["U"]):
    # embeddings shape : [vocab_size, dimension]
    embedding_norms = np.linalg.norm(embeddings, axis=1)
    query_vector = embeddings[word_to_index[query_word]] / np.linalg.norm(embeddings[word_to_index[query_word]])
    cosine_simiarities = []
    for word_idx, (word_vector, norm) in enumerate(zip(embeddings, np.linalg.norm(embeddings, axis=1))): #norm 은 벡터의 기본 단위
        cosine_similarity = np.dot(query_vector, word_vector / norm) # 코사인 시밀리리티를 높은 순서대로 소팅해서 보여주는 함수 식
        cosine_simiarities.append([index_to_word[word_idx], cosine_similarity])
    return sorted(cosine_simiarities, key=lambda x: x[1], reverse=True)[1:topn+1]

In [167]:
most_similar("파우스트", embeddings=parameters["U"])

[['합창', 0.860891544813731],
 ['리스트', 0.809214421055517],
 ['교향곡', 0.7665473305590378]]

In [168]:
most_similar("파우스트", embeddings=parameters["V"].T)

[['리스트', 0.8790272358310585],
 ['바그너', 0.7995338320144508],
 ['교향곡', 0.7667084425587315]]

In [169]:
most_similar("파우스트", embeddings=parameters["U"] + parameters["V"].T)

[['리스트', 0.8787869285331069],
 ['바그너', 0.8022084984560485],
 ['교향곡', 0.7725660366818604]]

In [170]:
most_similar("파우스트", embeddings=np.concatenate((parameters["U"], parameters["V"].T), axis=1))

[['리스트', 0.8790159245416065],
 ['바그너', 0.7995176668297033],
 ['교향곡', 0.766707850466573]]

### 학습된 모델 중에 u랑 v의 임베딩을 직접 쓴다 
### mse - regression모델 / 딥 러닝 cross entropy => 둘다 loss function 이라는 점에서 비슷하다 
### cos sim이 높다? -> 관련성이 높다 