In [5]:
import numpy.random

In [10]:
# 음이항 분포
numpy.random.negative_binomial(10,.4,100) + 10
# 앞면이 10번 나올 확률이 .4일 때, 100명의 사람들이 앞면이 10번 나올 때까지 돌려본 횟수를 구하려면 뒤에 
# n번 나올 때까지 + n번을 더해줘야함. 

array([18, 21, 26, 22, 26, 21, 29, 19, 22, 24, 34, 18, 20, 12, 36, 27, 40,
       30, 32, 25, 36, 39, 26, 24, 25, 32, 21, 25, 32, 18, 16, 39, 19, 17,
       44, 23, 26, 29, 23, 23, 24, 31, 19, 20, 19, 29, 28, 27, 33, 26, 23,
       23, 21, 22, 29, 25, 24, 44, 18, 20, 26, 25, 24, 21, 28, 28, 18, 23,
       26, 30, 21, 23, 19, 24, 20, 27, 19, 27, 30, 32, 24, 19, 18, 29, 28,
       18, 20, 22, 17, 23, 25, 27, 23, 17, 25, 14, 32, 23, 16, 30])

In [11]:
numpy.random.geometric(.1,100)
# 성공률이 .1 일 때, 100번 돌렸을 때 성공할 때까지 시도한 총 시도 횟수 

array([ 7,  9,  7,  5, 14, 19,  7, 12,  3,  8,  1, 11,  1,  5,  5,  8,  7,
        1, 15, 12, 11,  2,  3, 24,  2,  8, 16, 14, 27, 55,  2,  1,  5, 11,
        6,  2,  2, 20,  9,  1, 34, 13,  7,  1,  4,  2, 36, 21, 16,  4,  7,
       20,  8,  9,  4, 23,  8, 13,  1, 36, 24,  3, 12,  8,  1, 29,  4, 12,
        5, 55,  6,  2,  3,  3, 12, 21,  6, 15,  6,  4, 12, 10, 11,  1, 13,
        6,  8,  1,  5,  2,  3, 11,  3, 10,  9,  2, 19,  6,  3, 37])

In [12]:
# imputation 
from sklearn.impute import SimpleImputer

In [13]:
imp = SimpleImputer()

In [14]:
import numpy as np

In [15]:
import pandas as pd

In [17]:
df = pd.DataFrame([[1,2],[np.nan,3],[7,6]])

In [18]:
df

0  1
0  1.0  2
1  NaN  3
2  7.0  6

In [20]:
imp.fit_transform(df)

array([[1., 2.],
       [4., 3.],
       [7., 6.]])

# 화재 데이터로 살펴보기 

In [26]:
fire = pd.read_csv('1112_PJT002_train.csv')

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [27]:
pd.set_option('display.max_columns',None)

In [28]:
fire.head()

id             dt_of_fr    bldng_us bldng_archtctr  bldng_cnt  \
0  133759  2015-10-03 02:33:46         NaN            NaN          3   
1   96248  2016-11-13 17:05:57        업무시설       철근콘크리트구조          3   
2   71317  2016-11-21 12:46:36        단독주택           블록구조          4   
3   86638  2016-11-07 02:50:14  위험물저장및처리시설           벽돌구조          2   
4   97748  2014-01-28 16:36:43         NaN            NaN          4   

   bldng_ar   ttl_ar  lnd_ar dt_of_athrztn  ttl_grnd_flr  ttl_dwn_flr  \
0    112.86   112.86   200.0           NaN           1.0          0.0   
1    721.82  1109.54     0.0    1.9881e+07           5.0          0.0   
2     47.06    47.06   288.0   1.96501e+07           1.0          0.0   
3    171.45   176.64  1379.0   2.00201e+07           2.0          0.0   
4      0.00     0.00     0.0           NaN           NaN          NaN   

  bldng_us_clssfctn  tmprtr  prcpttn  wnd_spd  wnd_drctn  hmdt  \
0               NaN    15.8      NaN      1.6      360.0  73.0   
1               공공용    15.6      NaN      1.3       20.0  89.0   
2               주거용    15.7      NaN      4.3      360.0  74.0   
3               상업용    13.7      NaN      2.8      360.0  77.0   
4               NaN    10.4      NaN      4.7      320.0  15.0   

   gas_engry_us_201401  ele_engry_us_201401  gas_engry_us_201402  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  NaN                  0.0                  NaN   
4                  0.0                  0.0                  0.0   

   ele_engry_us_201402  gas_engry_us_201403  ele_engry_us_201403  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  0.0                  NaN                  0.0   
4                  0.0                  0.0                  0.0   

   gas_engry_us_201404  ele_engry_us_201404  gas_engry_us_201405  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  NaN                  0.0                  NaN   
4                  0.0                  0.0                  0.0   

   ele_engry_us_201405  gas_engry_us_201406  ele_engry_us_201406  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  0.0                  NaN                  0.0   
4                  0.0                  0.0                  0.0   

   gas_engry_us_201407  ele_engry_us_201407  gas_engry_us_201408  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  NaN                  0.0                  NaN   
4                  0.0                  0.0                  0.0   

   ele_engry_us_201408  gas_engry_us_201409  ele_engry_us_201409  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3                  0.0                  NaN                  0.0   
4                  0.0                  0.0                  0.0   

   gas_engry_us_201410  ele_engry_us_201410  gas_engry_us_201411  \
0                  NaN                  NaN                  NaN   
1                  0.0                  0.0                  0.0   
2                  NaN                  NaN                  NaN   
3           

In [33]:
fire[['bldng_ar','bldng_cnt']]

bldng_ar  bldng_cnt
0        112.86          3
1        721.82          3
2         47.06          4
3        171.45          2
4          0.00          4
...         ...        ...
59194    167.67          1
59195     57.38          2
59196    126.32          2
59197      0.00          4
59198    137.67          3

[59199 rows x 2 columns]

In [34]:
pd.DataFrame(imp.fit_transform(fire[['bldng_ar','bldng_cnt']]))
# 패키지에 따라서 계산하는 방법이 다른데, simpleimputer는 무슨 값으로 했는 지는 찾아야함. 

0    1
0      112.86  3.0
1      721.82  3.0
2       47.06  4.0
3      171.45  2.0
4        0.00  4.0
...       ...  ...
59194  167.67  1.0
59195   57.38  2.0
59196  126.32  2.0
59197    0.00  4.0
59198  137.67  3.0

[59199 rows x 2 columns]

In [37]:
from imblearn.over_sampling import SMOTE

ModuleNotFoundError: No module named 'imblearn'

In [38]:
ad = SMOTE()

NameError: name 'SMOTE' is not defined

In [39]:
X = fire[['blding_cont']]

KeyError: "None of [Index(['blding_cont'], dtype='object')] are in the [columns]"

In [ ]:
Y = fire['fr_yn']

In [ ]:
X_res, Y_res = ad.fit_resample(X,Y) # 두 데이터 비율을 1:1로 만들기 # y안에 있는 화재, 비화재 데이터를 반반으로 맞춰줌 

In [ ]:
X.shape

In [ ]:
X_res.shape #x와 y 데이터 오버 샘플링 값

In [ ]:
(Y == 'N').mean() # 0.83 정도였는데 

In [ ]:
(Y_res == 'N').mean() # 0.5로 맞춰짐 

In [ ]:
from imblearn.over_sampling import RandomUnderSampler

In [ ]:
rus = RandomUndersampler()

In [ ]:
X_res, Y_res = rus.fit_resample(X,Y) # 두 데이터 비율을 1:1로 만들기

In [ ]:
# 비워져있는 데이터 수동으로 채우지 마시고 imputation으로 채우세요 

In [40]:
# r 제곱 

In [43]:
df =pd.DataFrame({'x':[1,2,3,4,5], 'y':[1,3,5,3,7]})

In [44]:
df

x  y
0  1  1
1  2  3
2  3  5
3  4  3
4  5  7

In [45]:
df['y'].var()

5.2

In [46]:
df['y'].mean()

3.8

In [48]:
1 - np.mean((df['y']-df['x'])**2)/df['y'].var() 

0.6153846153846154

In [49]:
# 클러스터링